//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlalaPascal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StopAffterFirstErrorCheck {
            get {
                return ((bool)(this["StopAffterFirstErrorCheck"]));
            }
            set {
                this["StopAffterFirstErrorCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowLABELandGOTO {
            get {
                return ((bool)(this["AllowLABELandGOTO"]));
            }
            set {
                this["AllowLABELandGOTO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableMacros {
            get {
                return ((bool)(this["EnableMacros"]));
            }
            set {
                this["EnableMacros"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowInline {
            get {
                return ((bool)(this["AllowInline"]));
            }
            set {
                this["AllowInline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncludeAssertionCode {
            get {
                return ((bool)(this["IncludeAssertionCode"]));
            }
            set {
                this["IncludeAssertionCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseAnsiString {
            get {
                return ((bool)(this["UseAnsiString"]));
            }
            set {
                this["UseAnsiString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoadKylixcompact {
            get {
                return ((bool)(this["LoadKylixcompact"]));
            }
            set {
                this["LoadKylixcompact"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowSTATICinObject {
            get {
                return ((bool)(this["AllowSTATICinObject"]));
            }
            set {
                this["AllowSTATICinObject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CLikeOperator {
            get {
                return ((bool)(this["CLikeOperator"]));
            }
            set {
                this["CLikeOperator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RangeChecking {
            get {
                return ((bool)(this["RangeChecking"]));
            }
            set {
                this["RangeChecking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StackChecking {
            get {
                return ((bool)(this["StackChecking"]));
            }
            set {
                this["StackChecking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IOChecking {
            get {
                return ((bool)(this["IOChecking"]));
            }
            set {
                this["IOChecking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IntegerOverflowChecking {
            get {
                return ((bool)(this["IntegerOverflowChecking"]));
            }
            set {
                this["IntegerOverflowChecking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ObjectMethodCallChecking {
            get {
                return ((bool)(this["ObjectMethodCallChecking"]));
            }
            set {
                this["ObjectMethodCallChecking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PositionIndepentCode {
            get {
                return ((bool)(this["PositionIndepentCode"]));
            }
            set {
                this["PositionIndepentCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CreateSmartlinkableUnits {
            get {
                return ((bool)(this["CreateSmartlinkableUnits"]));
            }
            set {
                this["CreateSmartlinkableUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GenerateSmallerCode {
            get {
                return ((bool)(this["GenerateSmallerCode"]));
            }
            set {
                this["GenerateSmallerCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseResisterVariable {
            get {
                return ((bool)(this["UseResisterVariable"]));
            }
            set {
                this["UseResisterVariable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UncertainOptimizations {
            get {
                return ((bool)(this["UncertainOptimizations"]));
            }
            set {
                this["UncertainOptimizations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Level1Optimizations {
            get {
                return ((bool)(this["Level1Optimizations"]));
            }
            set {
                this["Level1Optimizations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Level2Optimizations {
            get {
                return ((bool)(this["Level2Optimizations"]));
            }
            set {
                this["Level2Optimizations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Level3Optimizations {
            get {
                return ((bool)(this["Level3Optimizations"]));
            }
            set {
                this["Level3Optimizations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F")]
        public char CompilerMode {
            get {
                return ((char)(this["CompilerMode"]));
            }
            set {
                this["CompilerMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public char OptimizationTargetProcessor {
            get {
                return ((char)(this["OptimizationTargetProcessor"]));
            }
            set {
                this["OptimizationTargetProcessor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public char CodeGenerationTargetProcessor {
            get {
                return ((char)(this["CodeGenerationTargetProcessor"]));
            }
            set {
                this["CodeGenerationTargetProcessor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public char VerboseSwitches {
            get {
                return ((char)(this["VerboseSwitches"]));
            }
            set {
                this["VerboseSwitches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N")]
        public char Brownser {
            get {
                return ((char)(this["Brownser"]));
            }
            set {
                this["Brownser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public char AssemblerReader {
            get {
                return ((char)(this["AssemblerReader"]));
            }
            set {
                this["AssemblerReader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Warnings {
            get {
                return ((bool)(this["Warnings"]));
            }
            set {
                this["Warnings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Notes {
            get {
                return ((bool)(this["Notes"]));
            }
            set {
                this["Notes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Hints {
            get {
                return ((bool)(this["Hints"]));
            }
            set {
                this["Hints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GeneralInfo {
            get {
                return ((bool)(this["GeneralInfo"]));
            }
            set {
                this["GeneralInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseTryedInfo {
            get {
                return ((bool)(this["UseTryedInfo"]));
            }
            set {
                this["UseTryedInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool All {
            get {
                return ((bool)(this["All"]));
            }
            set {
                this["All"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowallProcedures {
            get {
                return ((bool)(this["ShowallProcedures"]));
            }
            set {
                this["ShowallProcedures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListSource {
            get {
                return ((bool)(this["ListSource"]));
            }
            set {
                this["ListSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListRegisterAllocation {
            get {
                return ((bool)(this["ListRegisterAllocation"]));
            }
            set {
                this["ListRegisterAllocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListTempAllocation {
            get {
                return ((bool)(this["ListTempAllocation"]));
            }
            set {
                this["ListTempAllocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListNodeAllocation {
            get {
                return ((bool)(this["ListNodeAllocation"]));
            }
            set {
                this["ListNodeAllocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UsePipeWithAssembler {
            get {
                return ((bool)(this["UsePipeWithAssembler"]));
            }
            set {
                this["UsePipeWithAssembler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConditionalDefines {
            get {
                return ((string)(this["ConditionalDefines"]));
            }
            set {
                this["ConditionalDefines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AdditionalCompilerArgs {
            get {
                return ((string)(this["AdditionalCompilerArgs"]));
            }
            set {
                this["AdditionalCompilerArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string StackSize {
            get {
                return ((string)(this["StackSize"]));
            }
            set {
                this["StackSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string HeapSize {
            get {
                return ((string)(this["HeapSize"]));
            }
            set {
                this["HeapSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowToolBar {
            get {
                return ((bool)(this["ShowToolBar"]));
            }
            set {
                this["ShowToolBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowFoldingLines {
            get {
                return ((bool)(this["ShowFoldingLines"]));
            }
            set {
                this["ShowFoldingLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowBullentin {
            get {
                return ((bool)(this["ShowBullentin"]));
            }
            set {
                this["ShowBullentin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowHighlightCurrentLine {
            get {
                return ((bool)(this["ShowHighlightCurrentLine"]));
            }
            set {
                this["ShowHighlightCurrentLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FullScreen {
            get {
                return ((bool)(this["FullScreen"]));
            }
            set {
                this["FullScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Sound {
            get {
                return ((bool)(this["Sound"]));
            }
            set {
                this["Sound"] = value;
            }
        }
    }
}
